development:
  adapter: postgresql
  encoding: unicode
  database: tasktime_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tasktime_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: tasktime_production
  pool: 5
