development:
  adapter: postgresql
  encoding: unicode
  database: productively_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: productively_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: productively_production
  pool: 5
